/*-
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Ported from Linux rtw88 reg.h, main.h and mac.h.
 * Copyright(c) 2018-2019  Realtek Corporation
 * Original license: GPL-2.0 OR BSD-3-Clause; see LICENSE in this directory.
 *
 * Only the definitions this driver uses are carried over.
 */

#ifndef _RTW88_REG_H_
#define _RTW88_REG_H_

#ifndef BIT
#define BIT(n)			(1U << (n))
#endif

/* System and power control. */
#define REG_SYS_FUNC_EN		0x0002
#define BIT_FEN_BB_RSTB		BIT(0)
#define BIT_FEN_BB_GLB_RST	BIT(1)
#define REG_SYS_PW_CTRL		0x0004
#define BIT_PFM_WOWL		BIT(3)
#define REG_RSV_CTRL		0x001C
#define REG_RF_CTRL		0x001F
#define BIT_RF_SDM_RSTB		BIT(2)
#define BIT_RF_RSTB		BIT(1)
#define BIT_RF_EN		BIT(0)
#define REG_EFUSE_CTRL		0x0030
#define BIT_EF_FLAG		BIT(31)
#define BIT_SHIFT_EF_ADDR	8
#define BIT_MASK_EF_ADDR	0x3ff
#define BITS_EF_ADDR		(BIT_MASK_EF_ADDR << BIT_SHIFT_EF_ADDR)
#define BIT_MASK_EF_DATA	0xff
#define REG_LDO_EFUSE_CTRL	0x0034
#define BIT_MASK_EFUSE_BANK_SEL	(BIT(8) | BIT(9))
#define BIT_LDO25_EN		BIT(7)
#define REG_GPIO_MUXCFG		0x0040
#define BIT_FSPI_EN		BIT(19)
#define BIT_WLRFE_4_5_EN	BIT(2)
#define REG_LED_CFG		0x004C
#define BIT_LNAON_SEL_EN	BIT(26)
#define BIT_PAPE_SEL_EN		BIT(25)
#define REG_PAD_CTRL1		0x0064
#define BIT_PAPE_WLBT_SEL	BIT(29)
#define BIT_LNAON_WLBT_SEL	BIT(28)
#define REG_HCI_OPT_CTRL	0x0074
#define BIT_USB_SUS_DIS		BIT(8)
#define REG_MCUFW_CTRL		0x0080
#define BIT_BOOT_FSPI_EN	BIT(20)
#define REG_WLRF1		0x00EC
#define BIT_WLRF1_BBRF_EN	(BIT(24) | BIT(25) | BIT(26))
#define REG_SYS_CFG1		0x00F0
#define BIT_RTL_ID		BIT(23)
#define BIT_RF_TYPE_ID		BIT(27)
#define BIT_SHIFT_CHIP_VER	12
#define BIT_MASK_CHIP_VER	0xf
#define BIT_GET_CHIP_VER(x)	(((x) >> BIT_SHIFT_CHIP_VER) & BIT_MASK_CHIP_VER)

/* MAC. */
#define REG_CR			0x0100
#define REG_PCIE_RPWM		0x03D9	/* rtwdev->hci.rpwm_addr for PCIe */
#define BIT_RPWM_TOGGLE		BIT(7)
#define REG_CPU_DMEM_CON	0x1080
#define BIT_WL_PLATFORM_RST	BIT(16)
#define BIT_DDMA_EN		BIT(8)
#define REG_CR_EXT		0x1100

/* Power sequence commands (main.h). */
struct rtw_pwr_seq_cmd {
	uint16_t	offset;
	uint8_t		cut_mask;
	uint8_t		intf_mask;
	uint8_t		base:4;
	uint8_t		cmd:4;
	uint8_t		mask;
	uint8_t		value;
};

#define RTW_PWR_POLLING_CNT	20000

#define RTW_PWR_CMD_READ	0x00
#define RTW_PWR_CMD_WRITE	0x01
#define RTW_PWR_CMD_POLLING	0x02
#define RTW_PWR_CMD_DELAY	0x03
#define RTW_PWR_CMD_END		0x04

#define RTW_PWR_ADDR_MAC	0x00
#define RTW_PWR_ADDR_USB	0x01
#define RTW_PWR_ADDR_PCIE	0x02
#define RTW_PWR_ADDR_SDIO	0x03

#define RTW_PWR_INTF_SDIO_MSK	BIT(0)
#define RTW_PWR_INTF_USB_MSK	BIT(1)
#define RTW_PWR_INTF_PCI_MSK	BIT(2)
#define RTW_PWR_INTF_ALL_MSK	(BIT(0) | BIT(1) | BIT(2) | BIT(3))

#define RTW_PWR_CUT_TEST_MSK	BIT(0)
#define RTW_PWR_CUT_A_MSK	BIT(1)
#define RTW_PWR_CUT_B_MSK	BIT(2)
#define RTW_PWR_CUT_C_MSK	BIT(3)
#define RTW_PWR_CUT_D_MSK	BIT(4)
#define RTW_PWR_CUT_E_MSK	BIT(5)
#define RTW_PWR_CUT_F_MSK	BIT(6)
#define RTW_PWR_CUT_G_MSK	BIT(7)
#define RTW_PWR_CUT_ALL_MSK	0xFF

#define RTW_PWR_DELAY_US	0
#define RTW_PWR_DELAY_MS	1

#define cut_version_to_mask(cut) (0x1 << ((cut) + 1))

/* Firmware download (reg.h, fw.h). */
#define REG_SYS_CLK_CTRL	0x0008
#define BIT_CPU_CLK_EN		BIT(14)
#define BIT_WLMCU_IOIF		BIT(0)	/* in REG_RSV_CTRL + 1 */
#define BIT_FEN_CPUEN		BIT(2)	/* in REG_SYS_FUNC_EN + 1 */
#define BIT_MCUFWDL_EN		BIT(0)
#define BIT_IMEM_DW_OK		BIT(3)
#define BIT_IMEM_CHKSUM_OK	BIT(4)
#define BIT_DMEM_DW_OK		BIT(5)
#define BIT_DMEM_CHKSUM_OK	BIT(6)
#define BIT_CHECK_SUM_OK	(BIT(4) | BIT(6))
#define BIT_CPU_CLK_SEL		(BIT(12) | BIT(13))
#define BIT_FW_DW_RDY		BIT(14)
#define BIT_FW_INIT_RDY		BIT(15)
#define FW_READY		(BIT_FW_INIT_RDY | BIT_FW_DW_RDY | \
				 BIT_IMEM_DW_OK | BIT_DMEM_DW_OK | \
				 BIT_CHECK_SUM_OK)
#define FW_READY_MASK		(0xffff & ~BIT_CPU_CLK_SEL)
#define REG_TXDMA_PQ_MAP	0x010C
#define RTW_DMA_MAPPING_HIGH	3
#define BIT_HCI_TXDMA_EN	BIT(0)	/* REG_CR */
#define BIT_TXDMA_EN		BIT(2)	/* REG_CR */
#define BIT_ENSWBCN		BIT(8)	/* REG_CR */
#define REG_FIFOPAGE_CTRL_2	0x0204
#define BIT_MASK_BCN_HEAD_1_V1	0xfff
#define BIT_BCN_VALID_V1	BIT(15)
#define REG_TXDMA_STATUS	0x0210
#define BTI_PAGE_OVF		BIT(2)
#define REG_RQPN_CTRL_2		0x022C
#define BIT_LD_RQPN		BIT(31)
#define REG_FIFOPAGE_INFO_1	0x0230
#define REG_FWHW_TXQ_CTRL	0x0420
#define BIT_EN_BCNQ_DL		BIT(22)
#define REG_BCN_CTRL		0x0550
#define BIT_EN_BCN_FUNCTION	BIT(3)
#define BIT_DIS_TSF_UDT		BIT(4)
#define REG_FW_DBG7		0x10FC
#define FW_KEY_MASK		0xffffff00
#define ILLEGAL_KEY_GROUP	0xFAAAAA00
#define REG_DDMA_CH0SA		0x1200
#define REG_DDMA_CH0DA		0x1204
#define REG_DDMA_CH0CTRL	0x1208
#define BIT_DDMACH0_OWN		BIT(31)
#define BIT_DDMACH0_CHKSUM_EN	BIT(29)
#define BIT_DDMACH0_CHKSUM_STS	BIT(27)
#define BIT_DDMACH0_RESET_CHKSUM_STS BIT(25)
#define BIT_DDMACH0_CHKSUM_CONT	BIT(24)
#define BIT_MASK_DDMACH0_DLEN	0x3ffff
#define REG_H2CQ_CSR		0x1330
#define BIT_H2CQ_FULL		BIT(31)
#define OCPBASE_TXBUF_88XX	0x18780000
#define OCPBASE_DMEM_88XX	0x00200000

/* C2H event register and H2C packets (reg.h, fw.h). */
#define REG_C2HEVT		0x01A0
#define C2H_HW_FEATURE_REPORT	0x19
#define C2H_HW_FEATURE_DUMP	0xfd
#define HW_FEATURE_LEN		13
#define EFUSE_HW_CAP_IGNORE	0
#define EFUSE_HW_CAP_PTCL_VHT	3
#define EFUSE_HW_CAP_SUPP_BW80	7
#define EFUSE_HW_CAP_SUPP_BW40	6
#define RTW_BAND_2G_		BIT(0)	/* RTW_BAND_2G, for code outside port/ */
#define RTW_BAND_5G_		BIT(1)
#define RTW_CHANNEL_WIDTH_20	0
#define RTW_CHANNEL_WIDTH_40	1
#define RTW_CHANNEL_WIDTH_80	2
#define H2C_PKT_SIZE		32
#define H2C_PKT_HDR_SIZE	8
#define H2C_PKT_CMD_ID		0xFF
#define H2C_PKT_CATEGORY	0x01
#define H2C_PKT_GENERAL_INFO	0x0D
#define H2C_PKT_PHYDM_INFO	0x11
#define FW_RF_2T2R		2
#define FW_RF_1T1R		4
#define BB_PATH_A		BIT(0)
#define BB_PATH_B		BIT(1)
#define BB_PATH_AB		(BB_PATH_A | BB_PATH_B)
#define RF_1T1R			0
#define RF_2T2R			2	/* enum rtw_rf_type in main.h */

/* LTE coexistence indirect access (8822B has it). */
#define LTECOEX_ACCESS_CTRL	0x1700
#define LTECOEX_WRITE_DATA	0x1704
#define LTECOEX_READ_DATA	0x1708
#define LTECOEX_READY		BIT(29)

/* PCIe DMA (pci.h). */
#define RTK_PCI_CTRL		0x300
#define BIT_RST_TRXDMA_INTF	BIT(20)
#define BIT_RX_TAG_EN		BIT(15)
#define RTK_PCI_TXBD_DESA_BCNQ	0x308
#define RTK_PCI_TXBD_RWPTR_CLR	0x39C
#define RTK_PCI_TXBD_BCN_WORK	0x383
#define BIT_PCI_BCNQ_FLAG	BIT(4)
#define RTK_PCI_TXBD_OWN_OFFSET	15
#define RTK_PCI_TXBD_H2CQ_CSR	0x1330
#define BIT_CLR_H2CQ_HOST_IDX	BIT(16)
#define BIT_CLR_H2CQ_HW_IDX	BIT(8)
#define RTK_PCI_TXBD_DESA_H2CQ	0x1320
#define RTK_PCI_TXBD_DESA_MGMTQ	0x310
#define RTK_PCI_TXBD_DESA_BKQ	0x330
#define RTK_PCI_TXBD_DESA_BEQ	0x328
#define RTK_PCI_TXBD_DESA_VIQ	0x320
#define RTK_PCI_TXBD_DESA_VOQ	0x318
#define RTK_PCI_TXBD_DESA_HI0Q	0x340
#define RTK_PCI_RXBD_DESA_MPDUQ	0x338
#define RTK_PCI_TXBD_NUM_H2CQ	0x1328
#define RTK_PCI_TXBD_NUM_MGMTQ	0x380
#define RTK_PCI_TXBD_NUM_BKQ	0x38A
#define RTK_PCI_TXBD_NUM_BEQ	0x388
#define RTK_PCI_TXBD_NUM_VIQ	0x386
#define RTK_PCI_TXBD_NUM_VOQ	0x384
#define RTK_PCI_TXBD_NUM_HI0Q	0x38C
#define RTK_PCI_RXBD_NUM_MPDUQ	0x382
#define RTK_PCI_TXBD_IDX_H2CQ	0x132C
#define RTK_PCI_TXBD_IDX_MGMTQ	0x3B0
#define RTK_PCI_TXBD_IDX_BKQ	0x3AC
#define RTK_PCI_TXBD_IDX_BEQ	0x3A8
#define RTK_PCI_TXBD_IDX_VIQ	0x3A4
#define RTK_PCI_TXBD_IDX_VOQ	0x3A0
#define RTK_PCI_TXBD_IDX_HI0Q	0x3B8
#define RTK_PCI_RXBD_IDX_MPDUQ	0x3B4
#define RTK_PCI_HIMR0		0x0B0
#define RTK_PCI_HISR0		0x0B4
#define RTK_PCI_HIMR1		0x0B8
#define RTK_PCI_HISR1		0x0BC
#define RTK_PCI_HIMR3		0x10B8
#define RTK_PCI_HISR3		0x10BC
/* IMR 0 */
#define IMR_BCNDMAINT_E		BIT(14)
#define IMR_C2HCMD		BIT(10)
#define IMR_HIGHDOK		BIT(7)
#define IMR_MGNTDOK		BIT(6)
#define IMR_BKDOK		BIT(5)
#define IMR_BEDOK		BIT(4)
#define IMR_VIDOK		BIT(3)
#define IMR_VODOK		BIT(2)
#define IMR_RDU			BIT(1)
#define IMR_ROK			BIT(0)
/* IMR 1 */
#define IMR_TXFOVW		BIT(9)
/* IMR 3 */
#define IMR_H2CDOK		BIT(16)

/* TX packet descriptor (tx.h). 8822B: 48-byte packet descriptor. */
#define RTW_TX_DESC_W0_TXPKTSIZE_S	0	/* GENMASK(15, 0) */
#define RTW_TX_DESC_W0_OFFSET_S		16	/* GENMASK(23, 16) */
#define RTW_TX_DESC_W0_BMC		BIT(24)
#define RTW_TX_DESC_W0_LS		BIT(26)
#define RTW_TX_DESC_W0_DISQSELSEQ	BIT(31)
#define RTW_TX_DESC_W1_QSEL_S		8	/* GENMASK(12, 8) */
#define RTW_TX_DESC_W1_RATE_ID_S	16	/* GENMASK(20, 16) */
#define RTW_TX_DESC_W3_HW_SSN_SEL_S	6	/* GENMASK(7, 6) */
#define RTW_TX_DESC_W3_USE_RATE		BIT(8)
#define RTW_TX_DESC_W3_DISDATAFB	BIT(10)
#define RTW_TX_DESC_W4_DATARATE_S	0	/* GENMASK(6, 0) */
#define RTW_TX_DESC_W8_EN_HWSEQ		BIT(15)
#define TX_DESC_QSEL_BEACON		16
#define TX_DESC_QSEL_HIGH		17
#define TX_DESC_QSEL_MGMT		18
#define TX_DESC_QSEL_H2C		19
#define RTW_RATEID_G			7

/* main.h */
enum rtw_trx_desc_rate {
	DESC_RATE1M	= 0x00,
	DESC_RATE2M	= 0x01,
	DESC_RATE5_5M	= 0x02,
	DESC_RATE11M	= 0x03,

	DESC_RATE6M	= 0x04,
	DESC_RATE9M	= 0x05,
	DESC_RATE12M	= 0x06,
	DESC_RATE18M	= 0x07,
	DESC_RATE24M	= 0x08,
	DESC_RATE36M	= 0x09,
	DESC_RATE48M	= 0x0a,
	DESC_RATE54M	= 0x0b,

	DESC_RATEMCS0	= 0x0c,
	DESC_RATEMCS1	= 0x0d,
	DESC_RATEMCS2	= 0x0e,
	DESC_RATEMCS3	= 0x0f,
	DESC_RATEMCS4	= 0x10,
	DESC_RATEMCS5	= 0x11,
	DESC_RATEMCS6	= 0x12,
	DESC_RATEMCS7	= 0x13,
	DESC_RATEMCS8	= 0x14,
	DESC_RATEMCS9	= 0x15,
	DESC_RATEMCS10	= 0x16,
	DESC_RATEMCS11	= 0x17,
	DESC_RATEMCS12	= 0x18,
	DESC_RATEMCS13	= 0x19,
	DESC_RATEMCS14	= 0x1a,
	DESC_RATEMCS15	= 0x1b,
	DESC_RATEMCS16	= 0x1c,
	DESC_RATEMCS17	= 0x1d,
	DESC_RATEMCS18	= 0x1e,
	DESC_RATEMCS19	= 0x1f,
	DESC_RATEMCS20	= 0x20,
	DESC_RATEMCS21	= 0x21,
	DESC_RATEMCS22	= 0x22,
	DESC_RATEMCS23	= 0x23,
	DESC_RATEMCS24	= 0x24,
	DESC_RATEMCS25	= 0x25,
	DESC_RATEMCS26	= 0x26,
	DESC_RATEMCS27	= 0x27,
	DESC_RATEMCS28	= 0x28,
	DESC_RATEMCS29	= 0x29,
	DESC_RATEMCS30	= 0x2a,
	DESC_RATEMCS31	= 0x2b,

	DESC_RATEVHT1SS_MCS0	= 0x2c,
	DESC_RATEVHT1SS_MCS1	= 0x2d,
	DESC_RATEVHT1SS_MCS2	= 0x2e,
	DESC_RATEVHT1SS_MCS3	= 0x2f,
	DESC_RATEVHT1SS_MCS4	= 0x30,
	DESC_RATEVHT1SS_MCS5	= 0x31,
	DESC_RATEVHT1SS_MCS6	= 0x32,
	DESC_RATEVHT1SS_MCS7	= 0x33,
	DESC_RATEVHT1SS_MCS8	= 0x34,
	DESC_RATEVHT1SS_MCS9	= 0x35,

	DESC_RATEVHT2SS_MCS0	= 0x36,
	DESC_RATEVHT2SS_MCS1	= 0x37,
	DESC_RATEVHT2SS_MCS2	= 0x38,
	DESC_RATEVHT2SS_MCS3	= 0x39,
	DESC_RATEVHT2SS_MCS4	= 0x3a,
	DESC_RATEVHT2SS_MCS5	= 0x3b,
	DESC_RATEVHT2SS_MCS6	= 0x3c,
	DESC_RATEVHT2SS_MCS7	= 0x3d,
	DESC_RATEVHT2SS_MCS8	= 0x3e,
	DESC_RATEVHT2SS_MCS9	= 0x3f,

	DESC_RATEVHT3SS_MCS0	= 0x40,
	DESC_RATEVHT3SS_MCS1	= 0x41,
	DESC_RATEVHT3SS_MCS2	= 0x42,
	DESC_RATEVHT3SS_MCS3	= 0x43,
	DESC_RATEVHT3SS_MCS4	= 0x44,
	DESC_RATEVHT3SS_MCS5	= 0x45,
	DESC_RATEVHT3SS_MCS6	= 0x46,
	DESC_RATEVHT3SS_MCS7	= 0x47,
	DESC_RATEVHT3SS_MCS8	= 0x48,
	DESC_RATEVHT3SS_MCS9	= 0x49,

	DESC_RATEVHT4SS_MCS0	= 0x4a,
	DESC_RATEVHT4SS_MCS1	= 0x4b,
	DESC_RATEVHT4SS_MCS2	= 0x4c,
	DESC_RATEVHT4SS_MCS3	= 0x4d,
	DESC_RATEVHT4SS_MCS4	= 0x4e,
	DESC_RATEVHT4SS_MCS5	= 0x4f,
	DESC_RATEVHT4SS_MCS6	= 0x50,
	DESC_RATEVHT4SS_MCS7	= 0x51,
	DESC_RATEVHT4SS_MCS8	= 0x52,
	DESC_RATEVHT4SS_MCS9	= 0x53,

	DESC_RATE_MAX,
};

/* 8822B chip parameters (rtw8822b.c rtw8822b_hw_spec). */
#define RTW8822B_TX_PKT_DESC_SZ	48
#define RTW8822B_TX_BUF_DESC_SZ	16

/* Firmware file header (fw.h struct rtw_fw_hdr), little-endian. */
#define FW_HDR_SIZE		64
#define FW_HDR_CHKSUM_SIZE	8
#define FW_HDR_VERSION		0x04	/* le16 */
#define FW_HDR_SUBVERSION	0x06
#define FW_HDR_SUBINDEX		0x07
#define FW_HDR_MEM_USAGE	0x18
#define FW_HDR_H2C_FMT_VER	0x1C	/* le16 */
#define FW_HDR_DMEM_ADDR	0x20	/* le32 */
#define FW_HDR_DMEM_SIZE	0x24	/* le32 */
#define FW_HDR_IMEM_SIZE	0x30	/* le32 */
#define FW_HDR_EMEM_SIZE	0x34	/* le32 */
#define FW_HDR_EMEM_ADDR	0x38	/* le32 */
#define FW_HDR_IMEM_ADDR	0x3C	/* le32 */

/* MAC init: TX DMA queue mapping, FIFO pages, H2C queue (reg.h, mac.h). */
#define BIT_HCI_RXDMA_EN	BIT(1)	/* REG_CR */
#define BIT_RXDMA_EN		BIT(3)
#define BIT_PROTOCOL_EN		BIT(4)
#define BIT_SCHEDULE_EN		BIT(5)
#define BIT_MACTXEN		BIT(6)
#define BIT_MACRXEN		BIT(7)
#define MAC_TRX_ENABLE	(BIT_HCI_TXDMA_EN | BIT_HCI_RXDMA_EN | BIT_TXDMA_EN | \
			BIT_RXDMA_EN | BIT_PROTOCOL_EN | BIT_SCHEDULE_EN | \
			BIT_MACTXEN | BIT_MACRXEN)
#define BIT_TXDMA_VOQ_MAP(x)	(((x) & 0x3) << 4)
#define BIT_TXDMA_VIQ_MAP(x)	(((x) & 0x3) << 6)
#define BIT_TXDMA_BEQ_MAP(x)	(((x) & 0x3) << 8)
#define BIT_TXDMA_BKQ_MAP(x)	(((x) & 0x3) << 10)
#define BIT_TXDMA_MGQ_MAP(x)	(((x) & 0x3) << 12)
#define BIT_TXDMA_HIQ_MAP(x)	(((x) & 0x3) << 14)
#define RTW_DMA_MAPPING_EXTRA	0
#define RTW_DMA_MAPPING_LOW	1
#define RTW_DMA_MAPPING_NORMAL	2
#define REG_TRXFF_BNDY		0x0114
#define REG_RXFF_BNDY		0x011C
#define REG_AUTO_LLT_V1		0x0208
#define BIT_AUTO_INIT_LLT_V1	BIT(0)
#define REG_TXDMA_OFFSET_CHK	0x020C
#define REG_FIFOPAGE_INFO_2	0x0234
#define REG_FIFOPAGE_INFO_3	0x0238
#define REG_FIFOPAGE_INFO_4	0x023C
#define REG_FIFOPAGE_INFO_5	0x0240
#define REG_H2C_HEAD		0x0244
#define REG_H2C_TAIL		0x0248
#define REG_H2C_READ_ADDR	0x024C
#define REG_H2C_INFO		0x0254
#define BIT_EN_WR_FREE_TAIL	BIT(20)	/* REG_FWHW_TXQ_CTRL */
#define REG_BCNQ_BDNY_V1	0x0424
#define REG_BCNQ1_BDNY_V1	0x0456
#define REG_RCR			0x0608
#define BIT_APP_PHYSTS		BIT(28)
#define REG_RX_DRVINFO_SZ	0x060F
#define PHY_STATUS_SIZE		4
#define REG_WMAC_OPTION_FUNCTION 0x07D0
#define REG_H2C_PKT_READADDR	0x10D0
#define REG_H2C_PKT_WRITEADDR	0x10D4

#define TX_PAGE_SIZE_SHIFT		7
#define TX_PAGE_SIZE			(1 << TX_PAGE_SIZE_SHIFT)
#define RSVD_PG_H2C_EXTRAINFO_NUM	24
#define RSVD_PG_H2C_STATICINFO_NUM	8
#define RSVD_PG_H2CQ_NUM		8
#define RSVD_PG_CPU_INSTRUCTION_NUM	0
#define RSVD_PG_FW_TXBUF_NUM		4
#define C2H_PKT_BUF			256

/* 8822B MAC protocol/EDCA setup (rtw8822b.c, reg.h). */
#define REG_TCR			0x0604
#define REG_RX_PKT_LIMIT	0x060C
#define REG_RXFLTMAP0		0x06A0
#define REG_RXFLTMAP2		0x06A4
#define REG_SND_PTCL_CTRL	0x0718
#define BIT_DIS_CHK_VHTSIGB_CRC	BIT(6)
#define REG_EDCA_VO_PARAM	0x0500
#define REG_EDCA_VI_PARAM	0x0504
#define REG_PIFS		0x0512
#define REG_SIFS		0x0514
#define REG_SLOT		0x051B
#define REG_TX_PTCL_CTRL	0x0520
#define BIT_SIFS_BK_EN		BIT(12)
#define REG_TXPAUSE		0x0522
#define REG_TBTT_PROHIBIT	0x0540
#define REG_RD_NAV_NXT		0x0544
#define REG_DRVERLYINT		0x0558
#define REG_BCNDMATIM		0x0559
#define REG_RXTSF_OFFSET_CCK	0x055E
#define REG_TIMER0_SRC_SEL	0x05B4
#define BIT_TSFT_SEL_TIMER0	(BIT(4) | BIT(5) | BIT(6))
#define REG_AMPDU_MAX_TIME_V1	0x0455
#define REG_TX_HANG_CTRL	0x045E
#define BIT_EN_EOF_V1		BIT(2)
#define REG_SW_AMPDU_BURST_MODE_CTRL 0x04BC
#define BIT_PRE_TX_CMD		BIT(6)
#define REG_PROT_MODE_CTRL	0x04C8
#define REG_BAR_MODE_CTRL	0x04CC
#define REG_FAST_EDCA_VOVI_SETTING 0x1448
#define REG_FAST_EDCA_BEBK_SETTING 0x144C
#define BIT_SHIFT_SIFS_OFDM_CTX	8
#define BIT_SHIFT_SIFS_CCK_TRX	16
#define BIT_SHIFT_SIFS_OFDM_TRX	24
#define BIT_SHIFT_TBTT_HOLD_TIME_AP 8

#define RTW8822B_SYS_FUNC_EN	0xDC
#define RTW8822B_PHY_EFUSE_SIZE	1024
#define RTW8822B_LOG_EFUSE_SIZE	768
#define RTW8822B_PTCT_EFUSE_SIZE 96
#define RTW8822B_TXFF_SIZE	262144
#define RTW8822B_RXFF_SIZE	24576
#define RTW8822B_RSVD_DRV_PG_NUM 8
#define RTW8822B_CSI_BUF_PG_NUM	0

#endif /* _RTW88_REG_H_ */
